# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

parameters:
  - name: version
    displayName: Release version
    type: string
    default: internal

trigger: none

pool: Self-hosted agent pool  

steps:
- ${{ if eq(parameters.version, 'internal') }}:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: 'taolian/azure-agent'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: internal
- ${{ else }}:
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Hub'
      repository: 'taolian/azure-agent'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        ${{ parameters.version }}
        latest