version: "3.6"

services:
  azure-agent-dind:
    container_name: azure-agent-dind
    image: docker:dind
    privileged: true
    networks:
      - azure-agent
    ports:
      - 2375:2375 # non-tls port
      - 2376:2376 # tls port. more config will be needed to pass cert to other containers
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "DOCKER_TLS_CERTDIR=" # disable TLS

  azure-agent:
    container_name: azure-agent
    image: taolian/azure-agent:latest
    networks:
      - azure-agent
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "AZP_AGENT_NAME=change-me"
      - "AZP_POOL=change-me"
      - "AZP_TOKEN=change-me"
      - "AZP_URL=change-me"
      - "DOCKER_HOST=tcp://azure-agent-dind:2375"

networks:
  azure-agent: {}
